esphome:
  name: califood
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret ssid
  password: !secret wifipass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Califood Fallback Hotspot"
    password: !secretota

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret hapass
  services:
    - service: control_servo
      variables:
        level: float
      then:
        - servo.write:
            id: califood
            level: !lambda 'return level / 100.0;'

ota:
  password: !secret hapass

output:
  - platform: esp8266_pwm
    id: califood_output
    pin: D1
    frequency: 50 Hz
    
servo:
  - id: califood
    output: califood_output
    
sensor:
  - platform: uptime
    name: "Califood System Uptime"

  - platform: wifi_signal
    name: "Califood WiFi Signal"
    update_interval: 360s
    
  - platform: ultrasonic
    trigger_pin: D8
    echo_pin: D7
    name: "Cat Food Remaining"
    update_interval: 60s

time:
  - platform: homeassistant
    ## Set your timezone
    timezone: Europe/Madrid

switch:
  - platform: restart
    name: "Restart CatFeeder"
